version: '3'
services:
  user:
    build:
      context: backend/user-service
    ports:
      - "5000:5000"
    networks:
      - backend-network

  booking:
    build:
      context: ./backend/booking-service
    ports:
      - "5002:5002"
    networks:
      - backend-network

  flight:
    build:
      context: backend/flight-service
    ports:
      - "5001:5001"
    networks:
      - backend-network



networks:
  backend-network:
    driver: bridge