version: '3'
services:
  user:
    environment:
#      - REACT_APP_DB_HOST=${REACT_APP_DB_HOST}
      - REACT_APP_ORIGIN_URL=${REACT_APP_ORIGIN_URL}
    build:
      context: backend/user-service
    ports:
      - "5000:5000"
    networks:
      - backend-network

  booking:
    environment:
    #  - REACT_APP_DB_HOST=${REACT_APP_DB_HOST}
      - REACT_APP_ORIGIN_URL=${REACT_APP_ORIGIN_URL}
    build:
      context: ./backend/booking-service
    ports:
      - "5002:5002"
    networks:
      - backend-network

  flight:
    environment:
    #  - REACT_APP_DB_HOST=${REACT_APP_DB_HOST}
      - REACT_APP_ORIGIN_URL=${REACT_APP_ORIGIN_URL}
    build:
      context: backend/flight-service
    ports:
      - "5001:5001"
    networks:
      - backend-network



networks:
  backend-network:
    driver: bridge