version: '3'

services:
  user:
    environment:
      - DB_HOST=staging-aurora-cluster.cluster-cfcsa0sm2c8f.ap-northeast-2.rds.amazonaws.com
      - ORIGIN_URL=https://test.jawsfly.net
    build:
      context: backend/user-service
    ports:
      - "5000:5000"
    networks:
      - backend-network

  booking:
    environment:
      - DB_HOST=staging-aurora-cluster.cluster-cfcsa0sm2c8f.ap-northeast-2.rds.amazonaws.com
      - ORIGIN_URL=https://test.jawsfly.net
    build:
      context: ./backend/booking-service
    ports:
      - "5002:5002"
    networks:
      - backend-network

  flight:
    environment:
      - DB_HOST=staging-aurora-cluster.cluster-cfcsa0sm2c8f.ap-northeast-2.rds.amazonaws.com
      - ORIGIN_URL=https://test.jawsfly.net
    build:
      context: backend/flight-service
    ports:
      - "5001:5001"
    networks:
      - backend-network



networks:
  backend-network:
    driver: bridge