apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    kubernetes.io/cluster/jaws_prod_cluster: "owned"
  securityGroupSelector:
    kubernetes.io/cluster/jaws_prod_cluster: "owned"
  amiFamily: AL2
  